"""Archive format detection, extraction, and PDF rendering.

A comic is extracted *once* into a flat directory of sequentially-named page
images (``00000.jpg`` ...). Page order is established by natural-sorting the
image entries; non-image entries are dropped. Output filenames are generated by
index — archive-internal names are never used as output paths (Zip-Slip safe).

Dispatch is by content sniff, not extension, because some ``.cbz`` files are
actually 7-zip or RAR archives.
"""

from __future__ import annotations

import shutil
import subprocess
import zipfile
from pathlib import Path

try:  # POSIX-only; used to cap the size of any single file unar may write
    import resource
except ImportError:  # pragma: no cover - non-POSIX
    resource = None

from .util import ext_of, is_image, natural_sort_key

UNAR_TIMEOUT = 300  # seconds; guards against password prompts / pathological archives
PDF_RENDER_SCALE = 2.0  # 144 DPI (72 * 2); good balance of sharpness vs size
_COPY_CHUNK = 256 * 1024


class ArchiveError(Exception):
    """Raised when an archive cannot be opened/extracted (corrupt, encrypted, empty)."""


def _copy_capped(fsrc, fdst, remaining: int) -> int:
    """Copy fsrc -> fdst, raising ArchiveError if more than ``remaining`` bytes are
    read. Returns the budget left. Guards against decompression bombs that lie
    about their declared size."""
    while True:
        chunk = fsrc.read(_COPY_CHUNK)
        if not chunk:
            return remaining
        remaining -= len(chunk)
        if remaining < 0:
            raise ArchiveError("archive too large (exceeds extraction limit)")
        fdst.write(chunk)


def _tree_size(path: Path) -> int:
    total = 0
    for p in path.rglob("*"):
        try:
            if p.is_file() and not p.is_symlink():
                total += p.stat().st_size
        except OSError:
            pass
    return total


def sniff_format(path: Path) -> str:
    with open(path, "rb") as fh:
        head = fh.read(8)
    if head[:4] == b"%PDF":
        return "pdf"
    if head[:4] in (b"PK\x03\x04", b"PK\x05\x06", b"PK\x07\x08"):
        return "zip"
    if head[:7] == b"Rar!\x1a\x07\x00":
        return "rar4"
    if head[:8] == b"Rar!\x1a\x07\x01\x00":
        return "rar5"
    if head[:6] == b"7z\xbc\xaf\x27\x1c":
        return "7z"
    return "unknown"


def _finalize(images: list[Path], dest: Path, base_for_relsort: Path) -> list[str]:
    """Natural-sort image paths, move them into dest as NNNNN.ext, drop empties."""
    images = [p for p in images if p.is_file() and p.stat().st_size > 0]
    images.sort(key=lambda p: natural_sort_key(str(p.relative_to(base_for_relsort))))
    pages: list[str] = []
    for i, src in enumerate(images):
        ext = ext_of(src.name) or "jpg"
        out = f"{i:05d}.{ext}"
        src.replace(dest / out)
        pages.append(out)
    return pages


def _extract_zip(src: Path, dest: Path, max_bytes: int) -> list[str]:
    with zipfile.ZipFile(src) as zf:
        names = [n for n in zf.namelist() if not n.endswith("/") and is_image(n)]
        # Reject decompression bombs up front using the declared uncompressed sizes,
        # then enforce a hard cap during the copy in case the headers under-report.
        if sum(zf.getinfo(n).file_size for n in names) > max_bytes:
            raise ArchiveError("archive too large (uncompressed size exceeds limit)")
        names.sort(key=natural_sort_key)
        pages: list[str] = []
        remaining = max_bytes
        for i, name in enumerate(names):
            ext = ext_of(name) or "jpg"
            out = f"{i:05d}.{ext}"
            with zf.open(name) as fsrc, open(dest / out, "wb") as fdst:
                remaining = _copy_capped(fsrc, fdst, remaining)
            if (dest / out).stat().st_size == 0:
                (dest / out).unlink()
            else:
                pages.append(out)
    return pages


def _extract_unar(src: Path, dest: Path, max_bytes: int) -> list[str]:
    if shutil.which("unar") is None:
        raise ArchiveError("unar is not installed (required for CBR/7z archives)")
    raw = dest / "_raw"
    raw.mkdir(exist_ok=True)

    # Cap the size of any single file unar may write (decompression-bomb guard).
    preexec = None
    if resource is not None:
        def preexec() -> None:  # runs in the child after fork
            resource.setrlimit(resource.RLIMIT_FSIZE, (max_bytes, max_bytes))

    try:
        proc = subprocess.run(
            # "--" ends option parsing so an archive path can never be read as a flag.
            ["unar", "-q", "-D", "-f", "-o", str(raw), "--", str(src)],
            capture_output=True,
            timeout=UNAR_TIMEOUT,
            preexec_fn=preexec,
        )
    except subprocess.TimeoutExpired:
        shutil.rmtree(raw, ignore_errors=True)
        raise ArchiveError("extraction timed out (possibly password-protected)")
    if proc.returncode != 0:
        shutil.rmtree(raw, ignore_errors=True)
        raise ArchiveError("could not extract archive (corrupt, encrypted, or unsupported)")

    if _tree_size(raw) > max_bytes:
        shutil.rmtree(raw, ignore_errors=True)
        raise ArchiveError("archive too large (uncompressed size exceeds limit)")

    pages = _finalize(_collect_images(raw), dest, raw)
    shutil.rmtree(raw, ignore_errors=True)
    return pages


def _collect_images(raw: Path) -> list[Path]:
    """Regular image files that physically live inside ``raw`` — never symlinks, and
    never paths that resolve outside the extraction dir. An archive must not be able
    to smuggle in a link (e.g. ``page.jpg -> /etc/passwd``) and have it served."""
    raw_real = raw.resolve()
    images: list[Path] = []
    for p in raw.rglob("*"):
        try:
            if p.is_symlink() or not p.is_file() or not is_image(p.name):
                continue
            if not p.resolve().is_relative_to(raw_real):
                continue
        except OSError:
            continue
        images.append(p)
    return images


def _render_pdf(src: Path, dest: Path, max_pages: int) -> list[str]:
    import pypdfium2 as pdfium

    try:
        pdf = pdfium.PdfDocument(str(src))
    except Exception:  # corrupt / encrypted
        raise ArchiveError("cannot open PDF (corrupt or password-protected)")
    pages: list[str] = []
    try:
        n = len(pdf)
        if n > max_pages:
            raise ArchiveError(f"PDF has too many pages ({n} > {max_pages})")
        for i in range(n):
            try:
                bitmap = pdf[i].render(scale=PDF_RENDER_SCALE)
                pil = bitmap.to_pil().convert("RGB")
            except ArchiveError:
                raise
            except Exception:  # a single malformed page shouldn't 500 the request
                raise ArchiveError(f"failed to render PDF page {i}")
            out = f"{i:05d}.jpg"
            pil.save(dest / out, "JPEG", quality=85)
            pages.append(out)
    finally:
        pdf.close()
    return pages


def extract_to(
    src: Path, dest: Path, *, max_bytes: int = 4_000_000_000, max_pages: int = 3000
) -> tuple[str, list[str]]:
    """Extract all page images from ``src`` into ``dest``.

    ``max_bytes`` caps the total uncompressed size (decompression-bomb guard) and
    ``max_pages`` caps PDF page rendering. Returns ``(format, page_filenames)``.
    Raises :class:`ArchiveError` on failure or if no readable pages are found.
    """
    dest.mkdir(parents=True, exist_ok=True)
    fmt = sniff_format(src)

    if fmt == "pdf":
        pages = _render_pdf(src, dest, max_pages)
    elif fmt == "zip":
        try:
            pages = _extract_zip(src, dest, max_bytes)
        except zipfile.BadZipFile:
            pages = _extract_unar(src, dest, max_bytes)  # mislabeled (e.g. 7z) container
    else:  # rar4 / rar5 / 7z / unknown -> let unar try
        pages = _extract_unar(src, dest, max_bytes)

    if not pages:
        raise ArchiveError("no readable pages in archive")
    return fmt, pages


def page_dimensions(dest: Path, pages: list[str]) -> list[dict | None]:
    """Per-page {w,h} read from image headers (no full decode)."""
    from PIL import Image

    dims: list[dict | None] = []
    for name in pages:
        try:
            with Image.open(dest / name) as im:
                dims.append({"w": im.width, "h": im.height})
        except Exception:
            dims.append(None)
    return dims
